### ISSUE TITLE
Set `demo.druxtjs.org` as repository URL

### ISSUE THREAD

**Issue by mglaman** [druxt/umami.demo.druxtjs.org#12]
Not much of a feature, but a task: set `demo.druxtjs.org` as the repository URL for easier access.

**Comment by Decipher** [comment]
@mglaman Can you provide some more specifics on this issue?

I'm assuming you mean to add a `repository` property to the `package.json` file, but you may be referring to something else?

**Comment by mglaman** [comment]
I mean in the repository details on the GitHub repo. That way anyone browsing on GitHub can easily access the demo. I had to highlight the repo name and copy-paste it to visit the website :)

<img width="498" alt="Screen Shot 2020-09-28 at 7 44 06 PM" src="https://user-images.githubusercontent.com/3698644/94499700-017aaf00-01c3-11eb-80da-5f87adc13c28.png">

**Comment by Decipher** [comment]
Yeah right, totally missed your meaning. Done, thanks.
